### ISSUE TITLE
A friendlier way to return social media names

### ISSUE THREAD

**Issue by alifeinbinary** [webredone/theme-redone#2]
https://github.com/webredone/theme-redone/blob/2da961b696559f64a2c56ef71def156767e05652/php-inc/theme-functions.php#L514

Writing this function this way allows for social media links to inherit the TLD instead of filtering from an opinionated list. 
```
function tr_get_soc_name($soc_media_link) {
	$soc_media_name = parse_url($soc_media_link, PHP_URL_HOST);
	$domains = explode('.', $soc_media_name);

	return $domains[count($domains) - 2];
}
```

**Comment by nikola-wd** [comment]
Thanks, @alifeinbinary . This is a simpler solution, and I will make sure to include it in the next release. 

What comes to mind is actually creating 2 functions. For example `tr_extract_tld()` function, that can be used on its own for generic cases, and then also reusing it inside the `tr_get_soc_name()` function.

**Comment by alifeinbinary** [comment]
Can I submit a pull request to add this feature?
