### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by igorsamardzija** [webredone/theme-redone#4]
Hi,

Installed theme in Local , followed instructions from site (and closed issue) but still getting error. 

Vendor directory is not created. Views directory is created. 

Server started just fine.

Please check SS for details
https://prnt.sc/-94W7mnliBnp

Maybe I`m missing something

**Comment by nikola-wd** [comment]
Hi @igorsamardzija . Did you run `composer install`?

**Comment by igorsamardzija** [comment]
Hi @nikola-wd,

Yes I followed provided instructions.

**Comment by nikola-wd** [comment]
@igorsamardzija Can you please screenshot your theme directory (vendor should be there). 
And also, please run composer install again from the theme root, and screenshot the message that you get. P.S. (Minimum PHP version required as of the latest release is 8.0, maybe you are running on an older PHP version?) 

If you have Discord, please join via the link here so I can try to assist faster: https://webredone.com/theme-redone/support/

**Comment by nikola-wd** [comment]
Hi @igorsamardzija . 

Please do this from inside the terminal (the root of the theme):
`composer install` (After that's done, take a screenshot of the terminal output)

Also, please confirm that you used PHP version 8 or newer for Local, and not some of the previous versions.
